# Generated by Django 4.1.4 on 2022-12-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('empty', 'EMPTY'), ('Website: Non-Responsive', 'Website: Non-Responsive'), ('Website: Responsive', 'Website: Responsive'), ('Program: GUI', 'Program: Non-GUI'), ('Program: GUI', 'Program: GUI')], default='empty', max_length=50)),
                ('URL', models.URLField()),
                ('language_framework', models.CharField(max_length=30)),
            ],
        ),
    ]
